[2025-01-26T09:33:40.954+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-26T09:33:41.213+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_and_store_ebooks.create_table manual__2025-01-26T09:32:04.203533+00:00 [queued]>
[2025-01-26T09:33:41.377+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_and_store_ebooks.create_table manual__2025-01-26T09:32:04.203533+00:00 [queued]>
[2025-01-26T09:33:41.393+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-26T09:33:42.418+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): create_table> on 2025-01-26 09:32:04.203533+00:00
[2025-01-26T09:33:42.645+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=4752) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-26T09:33:42.748+0000] {standard_task_runner.py:72} INFO - Started process 4794 to run task
[2025-01-26T09:33:42.766+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'fetch_and_store_ebooks', 'create_table', 'manual__2025-01-26T09:32:04.203533+00:00', '--job-id', '1146', '--raw', '--subdir', 'DAGS_FOLDER/app.py', '--cfg-path', '/tmp/tmp8glcfdav']
[2025-01-26T09:33:42.801+0000] {standard_task_runner.py:105} INFO - Job 1146: Subtask create_table
[2025-01-26T09:33:44.025+0000] {task_command.py:467} INFO - Running <TaskInstance: fetch_and_store_ebooks.create_table manual__2025-01-26T09:32:04.203533+00:00 [running]> on host 34edd304782d
[2025-01-26T09:33:45.842+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='fetch_and_store_ebooks' AIRFLOW_CTX_TASK_ID='create_table' AIRFLOW_CTX_EXECUTION_DATE='2025-01-26T09:32:04.203533+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-26T09:32:04.203533+00:00'
[2025-01-26T09:33:45.848+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-26T09:33:45.898+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-26T09:33:45.918+0000] {logging_mixin.py:190} INFO - Current task name:create_table state:running start_date:2025-01-26 09:33:41.218809+00:00
[2025-01-26T09:33:45.937+0000] {logging_mixin.py:190} INFO - Dag name:fetch_and_store_ebooks and current dag run status:running
[2025-01-26T09:33:45.973+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-26T09:33:45.986+0000] {sql.py:278} INFO - Executing: 
    CREATE TABLE IF NOT EXISTS public.ebooks (
        id SERIAL PRIMARY KEY,
        judul TEXT NOT NULL,
        penulis TEXT,
        link TEXT
    );
    
[2025-01-26T09:33:46.170+0000] {base.py:84} INFO - Retrieving connection 'ebooks_connection'
[2025-01-26T09:33:46.458+0000] {base.py:84} INFO - Retrieving connection 'ebooks_connection'
[2025-01-26T09:33:46.852+0000] {sql.py:553} INFO - Running statement: 
    CREATE TABLE IF NOT EXISTS public.ebooks (
        id SERIAL PRIMARY KEY,
        judul TEXT NOT NULL,
        penulis TEXT,
        link TEXT
    );
    , parameters: None
[2025-01-26T09:33:46.997+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-26T09:33:47.037+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=fetch_and_store_ebooks, task_id=create_table, run_id=manual__2025-01-26T09:32:04.203533+00:00, execution_date=20250126T093204, start_date=20250126T093341, end_date=20250126T093347
[2025-01-26T09:33:47.427+0000] {logging_mixin.py:190} INFO - Task instance in success state
[2025-01-26T09:33:47.429+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-01-26T09:33:47.432+0000] {logging_mixin.py:190} INFO - Dag name:fetch_and_store_ebooks queued_at:2025-01-26 09:32:04.394771+00:00
[2025-01-26T09:33:47.441+0000] {logging_mixin.py:190} INFO - Task hostname:34edd304782d operator:PostgresOperator
[2025-01-26T09:33:47.730+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-26T09:33:47.853+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-01-26T09:33:48.211+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-26T09:33:48.243+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
